### ISSUE TITLE
Performance issue with getMagicItemDataFromItemStack()

### ISSUE THREAD

**Issue by kolderz** [TheComputerGeek2/MagicSpells#1035]
### Confirmation:

- [x] [My server is supported by MagicSpells.](https://github.com/TheComputerGeek2/MagicSpells/wiki/Supported-Versions)
- [x] This bug occurs on PaperMC itself, not just its forks which I might be using.

### Intended outcome:

getMagicItemDataFromItemStack() won't take too many server ticks.

### Actual outcome:

getMagicItemDataFromItemStack() takes too many server ticks.

<img width="638" alt="Image" src="https://github.com/user-attachments/assets/8779b6f0-ecb9-4db7-827b-eac94378cd0b" />

### Reproduction steps:

This is the spell I use to trigger that.
```
Sword_slash_passive:
    spell-class: ".PassiveSpell"
    always-granted: true
    triggers:
        - leftclickitem swordslash
    cooldown: 1
    spells:
        - spell_slash_1_1
``

### Errors:

```Shell
No error
```

### Relevant configuration:

```YAML

```

### MagicSpells version:

4.0-Beta-16

### Minecraft server version:

Purpur 1.21.4-2416-51aafbc (MC: 1.21.4)
