### ISSUE TITLE
ProjectileSpell's vertical and horizontal spread flattened when facing up or down

### ISSUE THREAD

**Issue by Iniquit** [TheComputerGeek2/MagicSpells#184]
The `horizontal-spread` and `vertical-spread` configuration options of the ProjectileSpell flatten into a line when the caster's pitch is significantly more or less than 0; the flattening effect becomes more pronounced the further the player's pitch is towards either 90 or -90.

Facing sideways (pitch 0):

![horizontal](https://user-images.githubusercontent.com/45113412/61097205-61ebc800-a428-11e9-9b24-35a24db27579.png)

Facing up (pitch -90):

![facing-up](https://user-images.githubusercontent.com/45113412/61097206-62845e80-a428-11e9-8a13-a06dadcdcbeb.png)

Facing down (pitch 90):

![facing-down](https://user-images.githubusercontent.com/45113412/61097207-62845e80-a428-11e9-928a-954f412549e1.png)

You can reproduce this issue by using the following example spell:
```
ExampleProj:
    spell-class: ".instant.ProjectileSpell"
    projectile-type: snowball
    horizontal-spread: 0.2
    vertical-spread: 0.2

ExampleMulti:
    spell-class: ".MultiSpell"
    spells:
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
        - ExampleProj
```

Versions:
Spigot: git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)
MagicSpells 4.0-SNAPSHOT
Effectlib: 6.1

The same spell cast on a Spigot 1.12.2 server running MagicSpells 3.6-dev-1902112318 worked correctly.
