### ISSUE TITLE
ItemProjectileSpell Doesn't Play Caster Effects

### ISSUE THREAD

**Issue by justinhschaaf** [TheComputerGeek2/MagicSpells#246]
Hello! When working with the `.instant.ItemProjectileSpell` today, I found that none of the caster spell effects I defined were playing; however, `special` effects still seem to work fine. I'm using MagicSpells 4.0 Beta-5 on Minecraft 1.15.2 with Paper-211. Thank you in advance for your time.

```yml
iceblock:
    spell-class: ".instant.ItemProjectileSpell"
    item: ice
    relative-offset: 0, 1, 0
    effects:
        sound:
            position: caster
            effect: sound
            sound: block.glass.break
            pitch: 1.5
        particle:
            position: caster
            effect: effectlib
            effectlib:
                class: CylinderEffect
                particle: block_crack
                particles: 25
                iterations: 1
                solid: false
                height: 0.1
                material: snow_block
                particle_offset_y: 1
```
