### ISSUE TITLE
How to use ImageEffect(Effectlib)

### ISSUE THREAD

**Issue by zhjlee11** [TheComputerGeek2/MagicSpells#452]
I wonder how to use ImageEffect...

```yml
TestImageEffect:
    spell-class: ".instant.DummySpell"
    str-cast-self: "casted"
    effects:
        1:
            position: caster
            effect: effectlib
            effectlib:
                class: ImageEffect
                invert: false
                file_name: "E:/user1/minecraft/Legacy of Network/server/plugins/MagicSpells/sword.png"
```

![sword](https://user-images.githubusercontent.com/38976987/117088499-8fd49600-ad8d-11eb-88ac-3e5efe713635.png)

I use this **512px x 512px PNG Image**. The image is located in **plugins/MagicSpells folder**.
I have already used "fileName" instead of "file_name" and relative path(plugins/MagicSpells/sword.png) instead of absolute path.

![image](https://user-images.githubusercontent.com/38976987/117088589-e0e48a00-ad8d-11eb-8913-27eaf871fa0e.png)
