### ISSUE TITLE
Target groups

### ISSUE THREAD

**Issue by DragonsAscent** [TheComputerGeek2/MagicSpells#540]
Target groups are groups defined in `general.yml` which can then be referred to in any area that supports targeting. So I could make my own target group called `undead` with a list of mobs such as ...
```yml
target-groups:
    undead:
        - zombie
        - skeleton
        - husk
        - stray
```
I would then be able to do `can-target: undead` to refer to this list. This would allow easier targeting for things like slimes and allow for greater control of targeting in general.
