### ISSUE TITLE
Add `cancel-on-fail` to Mutli/TMulti spells

### ISSUE THREAD

**Issue by DragonsAscent** [TheComputerGeek2/MagicSpells#541]
This option would completely remove all delayed actions passed one that fails.
```yml
Multi:
    spell-class: ".MultiSpell"
    spells:
        - Spell1
        - DELAY 10
        - Spell1
```
If `Spell1` fails to cast, it will try again in 10 ticks due to the task not being removed if a previous task failed. So if we add `cancel-on-fail` then every task after a failed spell will be cleared. Allows for cancelling of multi spells that cast over long periods of time via silence/modifiers.
