### ISSUE TITLE
RiptideSpell does not cancel on /ms reload if it has 0 duration

### ISSUE THREAD

**Issue by AkitoBurrito** [TheComputerGeek2/MagicSpells#555]
Not sure whether this is intentional or not, but if you configure a RiptideSpell to have 0 duration (indefinite duration) and do /ms reload, the animation continues after the reload. The reason I brought this up as an issue is because other spells that can have durations of 0, such as BuffSpells, cancel on /ms reload.

MagicSpells Version: 4.0-Beta-11

Config:
````yaml
RiptideSpell:
    spell-class: ".targeted.RiptideSpell" 
    target-self: true
    duration: 0
````

**Comment by AkitoBurrito** [comment]
Received confirmation that this is not a bug. Animation can be removed using a PassiveSpell with the "magicspellsloaded" trigger and a RidetideSpell with a duration of 1

MagicSpells Version: 4.0-Beta-11

Config:
````yaml
RiptideSpell:
    spell-class: ".targeted.RiptideSpell" 
    target-self: true
    duration: 0 

RiptideSpellReloadFix:
    spell-class: ".targeted.RiptideSpell" 
    target-self: true
    duration: 1 

RiptideReloadFixPassive:
    spell-class: ".PassiveSpell"
    triggers:
        - magicspellsloaded
    modifiers:
        - riptiding required
    spells:
        - RiptideSpellReloadFix(mode=full)
````
