### ISSUE TITLE
Spells listed under the "Spells" configuration option do not trigger when using Smith PassiveSpell trigger

### ISSUE THREAD

**Issue by AkitoBurrito** [TheComputerGeek2/MagicSpells#556]
When you create a PassiveSpell using the trigger "smith", spells listed under the "spells" configuration option are not casted when the PassiveSpell triggers (when you put an item in a smithing table slot). The unusual part is that the trigger is still activated and the cancel-default-action configuration option will cancel your attempt to smith an item if it is set to "true".

MagicSpells Version: 4.0-Beta-11
Config:

````yaml
smithtest_buffdummy:
    spell-class: ".buff.DummySpell"
    duration: 10
    target-self: true
    effects:
        eff1:
            position: buff
            effect: particles
            particle-name: REDSTONE
            color: 17B4DD
            relative-offset: 0,3,0
            horiz-spread: 0.1
            vert-spread: 0.1
            size: 1
            count: 10

smithltest_passive:
    spell-class: ".PassiveSpell"
    triggers:
        - smith
    cancel-default-action: false
    spells:
        - smithtest_buffdummy
 ````

**Comment by tonythemacaroni** [comment]
The passive is casting the buff spell - multiple times, in fact. Since the buff is not `toggle: false`, it's cancelling itself before the effects display. If you slightly modify the buff to have a fade message:
```yaml
smithtest_buffdummy:
    spell-class: ".buff.DummySpell"
    duration: 10
    target-self: true
    str-fade: "Faded."
    effects:
        eff1:
            position: buff
            effect: particles
            particle-name: REDSTONE
            color: 17B4DD
            relative-offset: 0,3,0
            horiz-spread: 0.1
            vert-spread: 0.1
            size: 1
            count: 10
```
You'll see that it fades multiple times. In my testing, it would consistently trigger six times, and thus, fade three times due to being `toggle: true` by default.
