### ISSUE TITLE
variable-mods-target changes caster's variables instead.

### ISSUE THREAD

**Issue by TheProPlayer1** [TheComputerGeek2/MagicSpells#57]
Variable 'test' for player 'Rifle_D_Luffy' modified by 1.0 as a result of spell casted 'lightningdummy'

```yml
variables:
    test:
        type: player
        min: 0
        max: 1
        default: 0
        permanent: false
lightningdummy:
    spell-class: ".targeted.PainSpell"
    cast-item: 265
    damage: 1
    require-entity-target: true
    variable-mods-target:
        - test 1
    effects:
        debug:
            position: target
            effect: sound
            sound: entity.player.attack.sweep
```
