### ISSUE TITLE
Config-based Spell Filter consistency

### ISSUE THREAD

**Issue by JasperLorelai** [TheComputerGeek2/MagicSpells#673]
2/13 classes which have the config-based SpellFilter use different keys for their spell filter config.
The first 11:
```yml
spells: []
denied-spells: []
spell-tags: []
denied-spell-tags: []
```
The other 2:
```yml
allowed-spells: []
disallowed-spells: []
allowed-spell-tags: []
disallowed-spell-tags: []
```
These are **SilenceSpell** and **NoMagicZone**.

In an effort for consistency and for easier extraction of duplicate code, these classes should use the first set of config keys.
